language: java

sudo: true

cache:
  directories:
  - $HOME/.m2

install: true

jdk:
 - oraclejdk8

env:
 - DISPLAY=:99.0

before_script:
 - sh -e /etc/init.d/xvfb start

script:
 - mvn -f org.assertx.swing.parent/pom.xml clean verify -Pjacoco
