language: java

sudo: false

cache:
  directories:
   - "$HOME/.m2"
   - "$HOME/.sonar/cache"

install: true

jdk: oraclejdk8

env:
 - DISPLAY=:99.0

addons:
  sonarcloud:
    branches:
     - sonarcloud
     - master
    organization: "cosimo5lli-github"

before_script:
 - sh -e /etc/init.d/xvfb start

script:
# jacoco profile enable the generation of coverage reports
# sonar-analysis profile is used to configure xtend compiler to not generate SuppressWarnings("All") annotation,
# that prevents Sonarqube analysis
 - mvn -f org.assertx.swing.parent/pom.xml clean verify -Pjacoco,sonar-analysis coveralls:report sonar:sonar
