/*
 * generated by Xtext 2.13.0
 */
package org.assertx.swing.ui.wizard;

import org.eclipse.ui.dialogs.WizardNewProjectCreationPage;

public class AssertXSwingWizardNewProjectCreationPage extends WizardNewProjectCreationPage {

	public AssertXSwingWizardNewProjectCreationPage(String pageName) {
		super(pageName);
	}

}
