/*
 * generated by Xtext 2.13.0
 */
package org.assertx.swing


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class AssertXSwingStandaloneSetup extends AssertXSwingStandaloneSetupGenerated {

	def static void doSetup() {
		new AssertXSwingStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
