/*
 * generated by Xtext 2.13.0
 */
package org.assertx.swing.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class AssertXSwingProposalProvider extends AbstractAssertXSwingProposalProvider {
}
